### ISSUE TITLE
2024-01-02 (화) 자료구조 & 알고리즘 

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#10]
### 🚀 스터디

* 일시: 2024-01-02 (화) 14:00 
* 장소: **이번 스터디는 Zoom** 으로 진행합니다. 동아리방에 와서 Zoom으로 진행해도 좋습니다.
* PR 마감 날짜: 1일 월 24시까지
* 참석자
  * 도연, 무준, 범수, 다빈

### 🎯 공통 주제

* 자료구조 나머지, 알고리즘

### 👩‍💻 개인 주제

* 공부하고 발표하고 싶은 주제 2개를 정해 이슈 답글을 달아주세요.
* 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다.
* 여기에 체크 후 Comment를 남겨 주세요.

- [x] 해시
- [ ] B - Tree & B + Tree
- [x] 그리디, 이분 탐색 (연관성이 없는 주제이나, 분량이 많지 않아서 묶었습니다.)
- [x] 다이나믹 프로그래밍
- [x] 정렬 1: 버블정렬, 선택정렬, 삽입정렬
- [x] 정렬 2: 퀵정렬, 병합 정렬, 힙 정렬
- [x] BFS, DFS
- [x] 완전 탐색
- [ ] 프림, 크루스칼 알고리즘(MST)
- [x] 다익스트라, 벨만-포드 알고리즘(최단 거리)
- [ ] 암호화 알고리즘

### ✔️ To Do

* `전날 자정(24:00:00)`까지 개인이 정리한 것을 PR 보내기. merge는 스터디 모임 때(이 내용을 토대로 발표)
* 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.
* 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)
* 커밋 양식은 #1 을 참고해주세요!

**Comment by nodb** [comment]
정렬 1: 버블정렬, 선택정렬, 삽입정렬
정렬 2: 퀵정렬, 병합 정렬, 힙 정렬
준비하겠습니다.

**Comment by megymj** [comment]
완전탐색과 최단 거리 알고리즘을 준비하겠습니다.

**Comment by sonemelody** [comment]
dp랑 dfs/bfs 준비하겠습니다.

**Comment by ninanoray** [comment]
해시, 그리디와 이분탐색 준비하겠습니다
