### ISSUE TITLE
2024-01-05 (금) 자료구조 & 알고리즘

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#18]
## 🚀 스터디
* 일시: 2024-01-05 (금) 14:00
* 장소: 비대면 Zoom
* 참석자
    * ~도연, 무준, 범수, 다빈~
    * `두 명이 불참하여서, 다음 주 금요일에 알고리즘도 같이 준비하는 것으로.`

## To do
* 댓글로 각자 자신이 공부해온 파트에 대한 예상 질문을 남겨주세요.
* 작성된 질문을 바탕으로, 다른 사람이 작성한 질문에 대한 답변을 각자 준비해옵니다.
* 5일 당일날, 랜덤으로 지정된 질문에 대한 답변을 진행합니다.

## Etc
* 개인 사정으로 인한 불참 혹은 대면이 힘든 상황이라 비대면으로 전환이 필요한 경우에는 미리 말해주세요

**Comment by megymj** [comment]
1. 다익스트라 알고리즘에 대해 아는 대로 설명해주세요
2. 다익스트라 알고리즘과 벨만-포드 알고리즘의 차이점에 대해 설명하세요
3. ~~다익스트라 알고리즘은 보통 우선순위 큐를 사용한다고 했는데, 그렇게 사용하면 생기는 이점은? (**이 부분은 제가 시간복잡도에 대한 설명을 추가해놓도록 하겠습니다**)~~

**참고 링크들**
https://kangsu-2ji.tistory.com/158
https://makefortune2.tistory.com/259

**Comment by sonemelody** [comment]
1. dfs와 bfs의 차이점을 설명하시오.
2. dfs를 사용해야 하는 경우와 bfs를 사용해야 하는 경우에 대해 설명하시오.
3. 다이나믹 프로그래밍과 메모이제이션에 대해 설명하시오.

**Comment by nodb** [comment]
### 퀵, 머지(합병), 버블이 주요하게 많이 나온다고 합니다.


* 왜 정렬 알고리즘이 많을까요?
    * 구체적인 Trade-off 예시
* 버블 정렬에 대해 설명해주세요.
* 선택 정렬에 대해 설명해주세요.
* 삽입 정렬에 대해 설명해주세요.
* 퀵 정렬에 대해 설명해주세요.
    * 수도코드 구현
    * 퀵소트의 장점과 단점이 뭐라고 생각하나요?
    * 최선/최악 시간복잡도 및 공간복잡도는 어떻게 되나요?
    * 성능을 개선시키려면 어떻게 해야할까요?
* 합병 정렬에 대해 설명해주세요.
    * 합병 정렬의 시간 복잡도는 어떻게 되나요?
* 힙 정렬이 유용한 경우를 설명해주세요.
* 대부분의 요소가 정렬되어있을때, 사용하기 적합한 정렬 알고리즘은?
* 안정 정렬인 정렬에는 무엇이 있나요?
* 퀵 정렬을 여러 언어의 정렬 내부 구현으로 사용하는 이유는?
* 100GB의 데이터를 1GB의 램으로 정렬하려면 어떻게 해야할까?

참고 링크
https://pinopino.tistory.com/entry/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%A9%B4%EC%A0%91-%EB%8C%80%EB%B9%84-%EC%A7%88%EB%AC%B8-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%97%85

**Comment by ninanoray** [comment]
## 해시

### 해시 테이블(Hash Table)과 시간 복잡도에 대해 설명해주세요

### Hash Map과 Hash Table의 차이점에 대해 설명해주세요

## 그리디

### 그리디 알고리즘을 간단히 설명하고 장단점에 대해 설명해주세요

## 이분 탐색

### 이분 탐색 알고리즘의 구현 방법을 설명하세요

### 이분 탐색 알고리즘을 기존의 순차 탐색과 비교해서 설명해주세요
