### ISSUE TITLE
2023-12-26 자료구조 - 1

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#2]
### 🚀 스터디
* 일시: ~2023-12-22 (금)~ 2023-12-26 (화) 14:00
* 장소: 미래관 123호
* PR 마감 날짜: ~21일 목 24시까지~ 25일 월 24시까지
* 참석자
    * 무준, 범수, 다빈

### 🎯 공통 주제
* 5.1 복잡도
* 5.2 선형 자료 구조
* 5.3 비선형 자료 구조

### 👩‍💻 개인 주제
* 공부하고 발표하고 싶은 주제 2개를 정해 이슈 답글을 달아주세요.
* 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다.
- [ ] 시간복잡도와 공간복잡도
- [x] 스택과 큐
- [x] 배열과 링크드 리스트
- [x] 트리
- [x] 이진 탐색 트리(레드 블랙 트리)
- [x] 그래프
- [x] 힙
- [ ] 해시
- [ ] B-Tree & B+Tree

### ✔️ To Do
* `전날 자정(24:00:00)`까지 개인이 정리한 것을 PR 보내기. merge는 스터디 모임 때(이 내용을 토대로 발표)
* 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.
* 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)
* 커밋 양식은 #1 을 참고해주세요!

**Comment by megymj** [comment]
예시)
 저는 트리와 이진 탐색 트리를 준비하겠습니다. 
-> 이후 위의 이슈에서 트리와 이진 탐색 트리를 체크하면 됩니다.

**Comment by megymj** [comment]
제가 먼저 선택하겠습니다.
저는 트리와 이진 탐색 트리에 대해 준비하겠습니다.

**Comment by nodb** [comment]
저는 그래프와 힙에 대해서 준비하겠습니다.

**Comment by ninanoray** [comment]
스택과 큐
배열과 링크드 리스트 공부하겠습니다

**Comment by megymj** [comment]
https://github.com/devSquad-study/2023-CS-Study/issues/1#issuecomment-1412451882 링크 참고하였음
## 👐 컨벤션
### 작성 방법
* 폴더와 파일명은 모두 영문 소문자로 작성한다.(공백은 '_'으로 채운다)

* 맨앞에 category를 포함해서 작성한다.

* 예) CPU 스케줄링 알고리즘 -> os_cpu_scheduling_and_algorithm.md

* 해당 문서를 다시 봤을 때, 추가적인 검색의 비용이 들지 않도록 쉽고 단순하게 작성한다.

* 제목이 길어져도 이해를 우선시하여 작성한다.

### 커밋 Convention
```
파일 생성 시 docs: [카테고리] md 파일 명
이미지 파일 업로드 시 add: [카테고리] 커밋 메시지
파일 내부 수정 시 chore: [카테고리] 커밋 메시지
파일명 수정 시 rename: [카테고리] 커밋 메시지
오류 처리시 fix: [카테고리] 커밋 메시지

CPU 스케줄링 알고리즘
예) docs: [OS] CPU 스케줄링 알고리즘
예) add: [OS] 파일 추가
예) chore: [OS] 내용 추가
예) rename: [OS] 이름 수정
예) fix: [OS] 오류 처리
```
