### ISSUE TITLE
2024-01-09 (화) 운영체제-1

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#21]
### 🚀 스터디

* 일시: 2024-01-09 (화) 14:00
* 장소: 미래관 123호
* PR 마감 날짜: 8일 월 24시까지
* 참석자
  * 도연, 무준, 범수, 다빈

### 🎯 공통 주제

* 운영체제

### 👩‍💻 개인 주제

* 공부하고 발표하고 싶은 주제 1개를 정해 이슈 답글을 달아주세요.
* 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다.
* 여기에 체크 후 Comment를 남겨 주세요.
* 자료구조, 알고리즘과는 달리 운영체제의 경우 파트를 결정하는게 쉽지 않아서, 아래에 있는 `주제 외에 본인이 공부하고 싶은 주제가 따로 있다면 그 주제를 공부해오셔도 좋습니다!`

- [x] deadlock
- [x] process and thread
- [x] cpu scheduling algorithm
- [x] memory structure

### ✔️ To Do

* `전날 자정(24:00:00)`까지 개인이 정리한 것을 PR 보내기. merge는 스터디 모임 때(이 내용을 토대로 발표)
* 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.
* 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)
* 커밋 양식은 #1 을 참고해주세요!

**Comment by nodb** [comment]
deadlock 공부해오겠습니다

**Comment by sonemelody** [comment]
process and thread 하겠습니다!

**Comment by megymj** [comment]
저는 memory structure로 준비하겠습니다.

**Comment by ninanoray** [comment]
CPU scheduling 준비하겠습니다
