### ISSUE TITLE
2024-01-12 (금) 운영체제 Q&A

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#26]
## 🚀 스터디

* 일시: 2024-01-12 (금) 11:00
* 장소: Google meet(비대면)
* 참석자
  * 도연, 무준, 범수, 다빈

## To do

* 댓글로 각자 자신이 공부해온 파트에 대한 예상 질문을 남겨주세요.
* 작성된 질문을 바탕으로, 다른 사람이 작성한 질문에 대한 답변을 각자 준비해옵니다.
* 12일 당일날, 랜덤으로 지정된 질문에 대한 답변을 진행합니다.

## Etc

* 개인 사정으로 인한 불참 혹은 대면이 힘든 상황이라 비대면으로 전환이 필요한 경우에는 미리 말해주세요

**Comment by megymj** [comment]
Q1. 만약 필요한 데이터가 하드디스크에 있다면, CPU에서 바로 하드디스크에 접근해서 데이터를 가져오면 더 빠를텐데 왜 굳이 모든 계층구조를 모두 통해서 가져올까요?

Q2. RAM을 주기억장치라고 표현하는 이유는?

Q3. 왜 불편하게 전원이 차단되면 모든 기억된 내용이 지워지는 휘발성 장치를 사용할까요?

**Comment by sonemelody** [comment]
1. 프로세스와 스레드의 개념에 대해 간략히 설명하세요.
2. 프로세스와 스레드의 차이점에 대해서 말하세요.
3. 멀티 프로세스와 멀티 스레드의 개념과 차이점에 대해서 간략히 말하세요.

**Comment by ninanoray** [comment]
1. CPU 스케줄링의 목적은 무엇입니까?
2. CPU 스케줄링은 언제 발생합니까?
3. 선점 스케줄링과 비선점 스케줄링의 차이점에 대해 설명해주세요.
4. SJF와 SRT를 비교해서 설명해주세요.
5. RR(Round Robin)에 대해 설명해주세요.

**Comment by nodb** [comment]
1. 데드락(DeadLock)에 대해 설명해보세요.
2. 데드락(DeadLock) 발생조건 4가지를 말해보세요.
3. 데드락(DeadLock) 해결 방법 4가지를 말해보세요.
4. 은행원 알고리즘(Banker Algorithm)에 대해 설명하세요.
5. 데드락(DeadLock)과 기아(Starvation)의 차이점에 대해 설명하세요.
