### ISSUE TITLE
2024-01-19 운영체제-2 Q&A

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#33]
## 🚀 스터디

* 일시: 2024-01-19 (금) 14:00
* 장소: Google meet(비대면)
* 참석자
  * 도연, 무준, 범수, 다빈

## To do

* 댓글로 각자 자신이 공부해온 파트에 대한 예상 질문을 남겨주세요.
* 작성된 질문을 바탕으로, 다른 사람이 작성한 질문에 대한 답변을 각자 준비해옵니다.
* 19일 당일날, 랜덤으로 지정된 질문에 대한 답변을 진행합니다.

## Etc

* 일정 의논 필요(다음 주부터)
* 운영체제를 한 주 더 할지, 아니면 다른 파트로 넘어갈지 의논 필요

**Comment by ninanoray** [comment]
- 힙 영역과 스택 영역을 비교해서 설명해주세요
- 메모리 구조에 대해 간단히 설명해주세요

- 논리적 주소와 물리적 주소에 대하여 설명해주세요
- 주소 바인딩에 대하여 설명해주세요
- MMU가 무엇인지 어떤 역할을 하는지 설명해주세요

**Comment by megymj** [comment]
* 가상 메모리의 개념이 무엇인가요?
* 요구 페이징의 개념을 설명하시오
* 스레싱이 무엇인지 설명하시오.
* 스레싱을 어떻게 해결할 수 있을까요?

**Comment by nodb** [comment]
- 인터럽트에 대해 설명해주세요.
- 내부/외부 인터럽트는 어떤 상황들이 있는지 말해보세요.
- 인터럽트와 트랩의 차이점
- 인터럽트 발생 시 처리 과정을 설명해주세요.
- 임계영역에 대해 설명해주세요.
	- 임계영역이 만족해야 하는 조건에 대해 설명해주세요.
- Race Condition(경쟁 상태)에 대해 설명해주세요.

**Comment by sonemelody** [comment]
1. 동기와 비동기에 대해서 설명하세요.
2. blocking과 non-blocking에 대해서 설명하세요.
3. 동기/비동기와 blocking/non-blocking의 차이에 대해서 설명하세요.
