### ISSUE TITLE
2024-01-26 네트워크-1 Q&A

### ISSUE THREAD

**Issue by megymj** [Network-Leader/2023-Winter-CS-Study#39]
## 🚀 스터디

* 일시: 2024-01-26 (금) 14:00
* 장소: Google meet(비대면)
* 참석자
  * 도연, 무준, 범수, 다빈

## To do

* 댓글로 각자 자신이 공부해온 파트에 대한 예상 질문을 남겨주세요.
* 작성된 질문을 바탕으로, 다른 사람이 작성한 질문에 대한 답변을 각자 준비해옵니다.
* 19일 당일날, 랜덤으로 지정된 질문에 대한 답변을 진행합니다.

## Etc

* 일정 의논 필요(다음 주부터)

**Comment by megymj** [comment]
Q1. REST API의 개념에 대해서 설명해주세요. 이 때, REST의 개념도 함께 말해주세요
Q2. API의 개념에 대해서 설명해주세요.
Q3. REST API 설계 예시를 아는 대로 말해주세요.

**Comment by nodb** [comment]
1. 쿠키와 세션을 사용하는 이유는 무엇인가요?
2. 쿠키와 세션의 차이점은 무엇인가요? 
3. 세션의 동작 방식은 어떻게 되나요?
4. 쿠키와 세션의 사용 예가 무엇이 있나요?

**Comment by ninanoray** [comment]
1. https://www.google.com 을 접속할 때 일어나는 일에 대해 통신 흐름의 관점으로 설명해주세요
2. DNS 서버에 대해 설명해주세요
3. DHCP에 대해 설명해주세요

**Comment by sonemelody** [comment]
1. origin이 무엇인가요?
2. SOP가 무엇인지 간단하게 설명하세요.
3. SOP를 하지 않는다면 어떤 문제가 발생할 수 있나요?
4. CORS가 무엇인지 간단하게 설명하세요.
